name: Deploy to prod

jobs:
  build:
    if: github.event.release.target_commitish == 'master'
    uses: ./.github/workflows/build-deploy-image.yml
    permissions:
      contents: "read"
      id-token: "write"
    with:
      imagename: 'prod-release-${{ github.ref_name }}'
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
  deploy:
    uses: ./.github/workflows/deploy-with-naisjob.yml
    needs: build
    with:
      naisCluster: prod-gcp
      xpAdminHost: portal-admin.oera.no
      image: ${{ needs.build.outputs.image }}
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}